#Credit to p4p1 for this code - https://github.com/p4p1/tryhackme-badge-workflow

name: TryHackMe Update Badge

on:
  schedule:
    # Make it run every 24 hour
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  tryhackme-badge-update:
    name: Update this repos tryhackme badge with the latest tryhackme image badge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          # Replace with your tryhackme username
          username: "WanderingPacket"
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
